// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.protbuf;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protbuf.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string RealName = 1;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>string RealName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();

  /**
   * <code>repeated .protbuf.Message.Instance instances = 2;</code>
   */
  java.util.List<sample.protbuf.Message.Instance> 
      getInstancesList();
  /**
   * <code>repeated .protbuf.Message.Instance instances = 2;</code>
   */
  sample.protbuf.Message.Instance getInstances(int index);
  /**
   * <code>repeated .protbuf.Message.Instance instances = 2;</code>
   */
  int getInstancesCount();
  /**
   * <code>repeated .protbuf.Message.Instance instances = 2;</code>
   */
  java.util.List<? extends sample.protbuf.Message.InstanceOrBuilder> 
      getInstancesOrBuilderList();
  /**
   * <code>repeated .protbuf.Message.Instance instances = 2;</code>
   */
  sample.protbuf.Message.InstanceOrBuilder getInstancesOrBuilder(
      int index);
}
