// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.protbuf;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protbuf.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protbuf.Response.ReturnCode returnCode = 1;</code>
   */
  int getReturnCodeValue();
  /**
   * <code>.protbuf.Response.ReturnCode returnCode = 1;</code>
   */
  sample.protbuf.Response.ReturnCode getReturnCode();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
